---
:api_key: cf9efad5ad37aa8c7684cbdb41890c29
:password: 7898b5172e4f50cdf1d25ab9b7cc5c7b
:theme_id: '30'
:preview_url: https://friendstore.commercesuite.com.br/loja/loja.php?loja=429889&opencode_theme=590b870425013
